sudo: required
services:
  - docker

before_install:
  - docker build -t muralidevops8080/murali90/docker-react -f Dockerfile.dev .

script:
    - docker run muralidevops8080/murali90/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: " DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-847374754482"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$ACCESS_PASS"

